# DaisySRV Configuration

# Discord Bot Configuration
discord:
  # Your Discord bot token (KEEP THIS SECRET!)
  token: "YOUR_BOT_TOKEN_HERE"

  # The Discord channel ID to send/receive messages
  channel-id: "YOUR_CHANNEL_ID_HERE"

# Console Log Configuration
console-log:
  # Whether to forward console messages to Discord
  enabled: false

  # The Discord role ID that is allowed to use the /console command
  whitelist-role: "YOUR_ADMIN_ROLE_ID_HERE"

  # The Discord channel ID for console command logs
  log-channel-id: "YOUR_CONSOLE_LOG_CHANNEL_ID_HERE"

# Message Format Configuration
format:
  # Format for Discord messages sent to Minecraft
  # Available placeholders: {username}, {message}
  discord-to-minecraft: "&b[Discord] &f{username}: &7{message}"

  # Format for Minecraft messages sent to Discord
  # Available placeholders: {username}, {message}
  minecraft-to-discord: "**{username}**: {message}"

# Embed Configuration
embeds:
  # Whether to use embeds for events
  enabled: true

  # Colors for different types of embeds (hex color codes)
  colors:
    join: "#55FF55"       # Green
    leave: "#FF5555"      # Red
    achievement: "#FFAA00" # Gold
    server: "#55FFFF"     # Aqua
    playerlist: "#5555FF" # Blue

# Event Configuration
events:
  # Whether to send messages when players join
  player-join: true

  # Whether to send messages when players leave
  player-quit: true

  # Whether to send messages when players earn achievements
  player-advancement: true

  # Whether to send a message when the server starts
  server-start: true

  # Whether to send a message when the server stops
  server-stop: true

# Command Configuration
commands:
  # Whether to enable Discord slash commands
  enabled: true

  # Whether to enable the playerlist command
  playerlist: true

# Bot Status Configuration
status:
  # Whether to show player count in bot status
  enabled: true

  # Type of status (PLAYING, WATCHING, LISTENING, COMPETING)
  type: "PLAYING"

  # Format for the status message
  # Available placeholders: {playerCount}, {maxPlayers}
  format: "{playerCount}/{maxPlayers} players online"

# Webhook Configuration
webhook:
  # Whether to use webhooks for player messages (shows player avatars and names)
  enabled: false

  # Your Discord webhook URL (KEEP THIS SECRET!)
  url: "YOUR_WEBHOOK_URL_HERE"

  # Default webhook name (used for system messages)
  name: "DaisySRV"

  # Avatar URL template for players (use {username} as placeholder)
  avatar-url: "https://www.mc-heads.net/avatar/{username}"

# General Settings
settings:
  # Whether to enable debug logging
  debug: false