name: DaisySRV
version: '1.1'
main: cat.daisy.daisySRV.DaisySRV
api-version: '1.21'
description: 'A simple Discord-Minecraft chat bridge'
authors: [ Daisy ]
website: https://daisy.cat

# Libraries - These will be downloaded by the server
libraries:
  # Kotlin dependencies
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.20

commands:
  ddiscord:
    description: DaisySRV main command
    usage: /ddiscord [reload]
    permission: daisysrv.admin

permissions:
  daisysrv.admin:
    description: Allows access to DaisySRV admin commands
    default: op
